#!/bin/bash
# This file will be sourced by the scripts automatically
MAKEFLAGS="-j4"
PKGEXT=".pkg.tar.zst"
#COMPRESSXZ=(xz -c -z - --threads=3)
COMPRESSZSTD=(zstd -c -z -q -12 -v -T3 -)
PACKAGER="Bruno Miguel <brunoalexandremiguel@gmail.com>"
#GPGKEY=""

REPONAME="userrepository"
REMOTE="/var/pkg/userrepository"
